export const SET_GEOLOCATION_LOOKUP_PENDING = 'SET_GEOLOCATION_LOOKUP_PENDING';
export const SET_GEOLOCATION_LOOKUP_SUCCESS = 'SET_GEOLOCATION_LOOKUP_SUCCESS';
export const SET_GEOLOCATION_LOOKUP_FAILURE = 'SET_GEOLOCATION_LOOKUP_FAILURE';

export const SET_COORDINATES = 'SET_COORDINATES';